---
EnableDefaultLinters: true
exclude:
  - "vendor/bundle/**/*"
  - "lib/kiqr/test/dummy/**/*"
linters:
  ErbSafety:
    enabled: true
  FinalNewline:
    enabled: true
  PartialInstanceVariable:
    enabled: true
  DeprecatedClasses:
    enabled: true
  HardCodedString:
    enabled: true
