name: Code review

on:
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - main

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run Danger
        run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.KIQRBOT_GITHUB_TOKEN }}
